---
title: "Brain slice visualization via the grammar of graphics"
format: html
---

## Introduction
Data visualization serves as the foundation for all scientific communication, and in the field of neuroscience, brain visualization serves as a central tool for the communication of research findings, creating grounds for vast software options to visualize brain images. Voxel-type visualization software commonly used by neuroscientists inlude ANTsR, ANTsPy, fsbrain, and RMINC, with the landscape ranging from straightforward to use while offering only specific plot types, to very complex visualization techniques for more flexible plotting of brain images, giving the user more control over the representation of the data. 

A middle ground can be found by employing the 'Grammar of Graphics' framework where brain images can be very flexibly plotted. In R, ‘ggplot2’ is a data visualization framework based on the 'Grammar of Graphics'. Similarly, the 'plotnine' package offers the same tools as 'ggplot2' in Python. By providing voxel-wise data in a tidy data frame, ‘ggplot2’ can present data after mapping a series of aesthetics and primitives. With the fundamental ideas of the 'Grammar of Graphics', complex visualizations and images can be generated by understanding how to layer each aesthetic and primitive, beyond basic charts and graphs. Complex images, such as atlas' overlayed on a brain image, can be created by ‘ggplot2’ and ‘plotnine’, which are versatile in displaying brain images beyond standard sagittal, coronal, and axial views, by understanding the 'Grammar of Graphics'. 

?A basic rundown of the 'Grammar of Graphics'?

The advantages of using a 'Grammar of Graphics' method of neuroimaging visualization is its seamless integration into the normal programming workflows that already use R and/or Python for data analysis and its versitality in producing any type of plot, from annotations to layering atlases. By harnessing the built-in framework found in 'gglot2' and/or 'plotnine', the workflow from data analysis to brain visualization no longer requires the use of multiple software options. With this, one can have make complex visuals from making multi-slice plots, annotated slices, and layering atlases all in one workspace that is not provided by many other packges.

The disadvantages of utilizing this framework arises mainly from the slightest learning curve that comes with learning the language of the 'Grammar of Graphics' and a requirement that the imaging data, including coordinates and voxel intensities, must be processed into a data frame in order to use the 'Grammar of Graphics' framework provided by 'ggplot2' or 'plotnine'. However, both this tutorial and a new image data processing package, 'ggslicer', were developped to address both those issues. This tutorial will provide a simple overview of a range of possible visualizations so that one may get comfortable with the framework. In addition, the 'ggslicer' package was developed with the purpose of processing images to return a dataframe with all the necessary information to use 'ggplot2' and 'plotnine'.

A tutorial for this method of voxel-type, code-based visualization is outlined below. The tutorial is presented in R with ‘ggplot2’ and in Python with the equivalent package 'plotnine'.

## Tutorial
# Prepare envireomnent and load the data
Before we start, 
Use the mni space template

```r
image <- "mni_icbm152_t1_tal_nlin_sym_09c.mnc"

coordinates <- slice_axis(image, "x", 10)

intensities <- slice_intensity(image, coordinates)
```
To view the data
```r
View(intensities)
```

# A simple plot
```r 
r

df_template_singleslice <- df_template %>%
    filter(x==10)
```
```python
python

df_template_singleslice = df_template[df_template["x"] == 10]
```



```r
r

ggplot(data=df_template_singleslice,
        mapping=aes(x=y, y=z)) +
    geom_raster(mapping=aes(fill=intensity))
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"))
)
```



```r
r

ggplot(data=df_template_singleslice,
            mapping=aes(x=y, y=z)) +
    geom_raster(mapping=aes(fill=intensity)) +
    coord_fixed(ratio=1)
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"))
    + coord_equal(ratio=1)
)
```





```r
r

ggplot(data=df_template_singleslice,
            mapping=aes(x=y, y=z)) +
    geom_raster(mapping=aes(fill=intensity)) +
    scale_fill_gradient(low='black', high='white') +
    coord_fixed(ratio=1)
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"))
    + scale_fill_gradient(low="black", high="white")
    + coord_equal(ratio=1)
)
```


# Customizing your plot
```r
r

df_template_singleslice_zoomedin <- df_template_singleslice %>% filter(y > -10, y < 20, z > -10, z < 20)

plt_without_interpolation <- ggplot(data=df_template_singleslice_zoomedin,
                                    mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate=F) +
  scale_fill_gradient(low='black', high='white', guide='none') +
  coord_fixed(ratio=1)

plt_with_interpolation <- ggplot(data=df_template_singleslice_zoomedin,
                                    mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate=T) +
  scale_fill_gradient(low='black', high='white', guide='none') +
  coord_fixed(ratio=1)

plt_without_interpolation + plt_with_interpolation
```
```python
python

df_template_singleslice_zoomedin = df_template_singleslice[
    (df_template_singleslice["y"] > -10)
    & (df_template_singleslice["y"] < 20)
    & (df_template_singleslice["z"] > -10)
    & (df_template_singleslice["z"] < 20)
]

plt_without_interpolation = (
    ggplot(data=df_template_singleslice_zoomedin, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation=None)
    + scale_fill_gradient(low="black", high="white", guide=None)
    + coord_equal(ratio=1)
)

plt_with_interpolation = (
    ggplot(data=df_template_singleslice_zoomedin, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", guide=None)
    + coord_equal(ratio=1)
)

# Using patchworklib syntax for side-by-side plotting:
patchworklib.load_ggplot(plt_without_interpolation) + patchworklib.load_ggplot(plt_with_interpolation)
```

```r
r

plt_with_raster <- ggplot(data=df_template_singleslice_zoomedin,
                                    mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate=F) +
  scale_fill_gradient(low='black', high='white') +
  coord_fixed(ratio=1) 

plt_with_point <- ggplot(data=df_template_singleslice_zoomedin,
              mapping=aes(x=y, y=z)) +
  geom_point(mapping=aes(color=intensity), size=1) +
  scale_color_gradient(low='black', high='white') +
  coord_fixed(ratio=1)

plt_with_raster + plt_with_point
```
```python
python

plt_with_raster = (
    ggplot(data=df_template_singleslice_zoomedin, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation=None)
    + scale_fill_gradient(low="black", high="white")
    + coord_equal(ratio=1)
)

plt_with_point = (
    ggplot(data=df_template_singleslice_zoomedin, mapping=aes(x="y", y="z"))
    + geom_point(mapping=aes(color="intensity"), size=1)
    + scale_color_gradient(low="black", high="white")
    + coord_equal(ratio=1)
)

patchworklib.load_ggplot(plt_with_raster) + patchworklib.load_ggplot(plt_with_point)
```

```r
r

ggplot(data=df_template_singleslice,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1)
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + coord_equal(ratio=1)
)
```


```r
r

ggplot(data=df_template_singleslice,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_bw() 
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_bw()
)
```

```r
r

ggplot(data=df_template_singleslice,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void()
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
)
```

```r
r

ggplot(data=df_template_singleslice,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void() +
  theme(axis.title=element_text(size=10))
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
    + theme(axis_title=element_text(size=10))
)
```

```r
r

ggplot(data=df_template_singleslice,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void() +
  theme(axis.title=element_text(size=10),
        axis.title.y = element_text(angle=90))
```
```python
python

(
    ggplot(data=df_template_singleslice, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
    + theme(
        axis_title=element_text(size=10),
        axis_title_y=element_text(angle=90)
    )
)
```

# Multi-slice plots
```r
r

ggplot(data=df_template,
       mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void() +
  theme(axis.title=element_text(size=10),
        axis.title.y = element_text(angle=90))
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
    + theme(
        axis_title=element_text(size=10),
        axis_title_y=element_text(angle=90)
    )
)
```

```r
r

ggplot(data=(df_template %>% arrange(slice_world)),
       mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void() +
  theme(axis.title=element_text(size=10),
        axis.title.y = element_text(angle=90))
```
```python
python

(
    ggplot(data=df_template.sort_values("slice_world"), mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
    + theme(
        axis_title=element_text(size=10),
        axis_title_y=element_text(angle=90)
    )
)
```

```r
r

ggplot(data=df_template,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  facet_wrap(~ slice_world) +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void() +
  theme(axis.title=element_text(size=10),
        axis.title.y = element_text(angle=90))
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(low="black", high="white", limits=(30, 90), oob=squish, guide=None)
    + facet_wrap("~slice_world")
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
    + theme(
        axis_title=element_text(size=10),
        axis_title_y=element_text(angle=90)
    )
)
```

```r
r

ggplot(data=df_template,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  facet_wrap(~ glue("x = {slice_world}")) +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void() +
  theme(axis.title=element_text(size=10),
        axis.title.y = element_text(angle=90))
```
```python
python

(
    ggplot(
        data=df_template.assign(
            slice_label=lambda df: "x = " + df["slice_world"].astype(str)
        ),
        mapping=aes(x="y", y="z"),
    )
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + facet_wrap("~slice_label")
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
    + theme(
        axis_title=element_text(size=10),
        axis_title_y=element_text(angle=90),
    )
)
```

```r
r

plt_with_space <- ggplot(data=df_template,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  facet_wrap(~ glue("x = {slice_world}")) +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_bw()

plt_without_space <- ggplot(data=df_template,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ glue("x = {slice_world}")) +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_bw()

plt_with_space + plt_without_space
```
```python
python

plt_with_space = (
    ggplot(
        data=df_template.assign(
            slice_label=lambda df: "x = " + df["slice_world"].astype(str)
        ),
        mapping=aes(x="y", y="z"),
    )
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + facet_wrap("~slice_label")
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_bw()
)

plt_without_space = (
    ggplot(
        data=df_template.assign(
            slice_label=lambda df: "x = " + df["slice_world"].astype(str)
        ),
        mapping=aes(x="y", y="z"),
    )
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_label")
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_bw()
)

patchwork.load_ggplot(plt_with_space) + patchwork.load_ggplot(plt_without_space)
```

```r
r

ggplot(data=df_template,
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ glue("x = {slice_world}")) +
  coord_fixed(ratio=1) +
  xlab("Posterior-Anterior") +
  ylab("Inferior-Superior") +
  theme_void() +
  theme(axis.title=element_text(size=10),
        axis.title.y = element_text(angle=90))
```
```python
python

(
    ggplot(
        data=df_template.assign(
            slice_label=lambda df: "x = " + df["slice_world"].astype(str)
        ),
        mapping=aes(x="y", y="z"),
    )
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_label")
    + coord_equal(ratio=1)
    + xlab("Posterior-Anterior")
    + ylab("Inferior-Superior")
    + theme_void()
    + theme(
        axis_title=element_text(size=10),
        axis_title_y=element_text(angle=90),
    )
)
```

```r
r

ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ slice_world) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(0, "npc"))
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_world")
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text=element_blank(),
        panel_spacing=0,  # Equivalent to unit(0, "npc") or 0 spacing in plotnine
    )
)
```

```r
r

ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ slice_world, ncol = 2) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(0, "npc"))
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_world", ncol=2)
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text=element_blank(),
        panel_spacing=0,
    )
)
```

# Layering stats maps

```r
r

ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  new_scale_fill() + 
  geom_raster(data=df_component1, mapping=aes(fill=intensity)) +
  scale_fill_gradient(name='Component\nvalue', low='darkred', high='yellow', limits=c(0.3, 0.5), na.value = 'transparent') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ slice_world, ncol=2) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(0, "npc"))
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(data=df_component1, mapping=aes(fill="intensity"))
    + scale_fill_gradient(
        name="Component\nvalue",
        low="darkred",
        high="yellow",
        limits=(0.3, 0.5),
        na_value="transparent",
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_world", ncol=2)
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text=element_blank(),
        panel_spacing=0,
    )
)
```

```r
r

ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(data=df_component1, mapping=aes(fill=intensity)) +
  scale_fill_gradient(low='darkred', high='yellow', limits=c(0.3, 0.5), na.value = 'transparent') +
  new_scale_fill() + 
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ slice_world, ncol=2) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(0, "npc"))
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(data=df_component1, mapping=aes(fill="intensity"))
    + scale_fill_gradient(
        low="darkred",
        high="yellow",
        limits=(0.3, 0.5),
        na_value="transparent",
    )
    + new_scale_fill()
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_world", ncol=2)
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text=element_blank(),
        panel_spacing=0,
    )
)
```

```r
r

ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  new_scale_fill() + 
  geom_raster(data=df_component1_lowres, mapping=aes(fill=intensity)) +
  scale_fill_gradient(name='Component\nvalue', low='darkred', high='yellow', limits=c(0.3, 0.5), na.value = 'transparent') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ slice_world, ncol=2) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(0, "npc"))
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(data=df_component1_lowres, mapping=aes(fill="intensity"))
    + scale_fill_gradient(
        name="Component\nvalue",
        low="darkred",
        high="yellow",
        limits=(0.3, 0.5),
        na_value="transparent",
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_world", ncol=2)
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text=element_blank(),
        panel_spacing=0,
    )
)
```

# Multiple stats maps
```r
r

# Component 1
ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  new_scale_fill() + 
  geom_raster(data=df_component1, mapping=aes(fill=intensity)) +
  scale_fill_gradient(name='Component\nvalue', low='darkred', high='yellow', limits=c(0.3, 0.5), na.value = 'transparent') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ slice_world, ncol=2) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(0, "npc"))
```
```python
python

# Component 1
(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(data=df_component1, mapping=aes(fill="intensity"))
    + scale_fill_gradient(
        name="Component\nvalue",
        low="darkred",
        high="yellow",
        limits=(0.3, 0.5),
        na_value="transparent",
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_world", ncol=2)
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text=element_blank(),
        panel_spacing=0,
    )
)
```

```r
r

# Component 2
ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  new_scale_fill() + 
  geom_raster(data=df_component2, mapping=aes(fill=intensity)) +
  scale_fill_gradient(name='Component\nvalue', low='darkred', high='yellow', limits=c(0.3, 0.5), na.value = 'transparent') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_wrap(~ slice_world, ncol=2) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text = element_blank(),
        panel.spacing = unit(0, "npc"))
```
```python
python

# Component 2
(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(data=df_component2, mapping=aes(fill="intensity"))
    + scale_fill_gradient(
        name="Component\nvalue",
        low="darkred",
        high="yellow",
        limits=(0.3, 0.5),
        na_value="transparent",
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_wrap("~slice_world", ncol=2)
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text=element_blank(),
        panel_spacing=0,
    )
)
```

```r
r

# Combine the data frames
# First add a new column called Component which we will facet by, and then bind rows
df_component1$Component <- "Component 1"
df_component2$Component <- "Component 2"
df_components_all <- bind_rows(df_component1, df_component2)

# Plot, this time faceting not just by slice_world but also by Component
# We'll use facet_grid instead of facet_wrap, so that columns correspond to components and rows correspond to the different sagittal slices
ggplot(data=(df_template),
              mapping=aes(x=y, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  new_scale_fill() + 
  geom_raster(data=df_components_all, mapping=aes(fill=intensity)) +
  scale_fill_gradient(name='Component\nvalue', low='darkred', high='yellow', limits=c(0.3, 0.5), na.value = 'transparent') +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  facet_grid(slice_world ~ Component) +
  coord_fixed(ratio=1) +
  theme_void() +
  theme(strip.text.y = element_blank(), 
        panel.spacing = unit(0, "npc"))
```
```python
python

# Combine the data frames
# First add a new column called Component which we will facet by, and then bind rows
df_component1["Component"] = "Component 1"
df_component2["Component"] = "Component 2"
df_components_all = pandas.concat([df_component1, df_component2], ignore_index=True)

# Plot, this time faceting not just by slice_world but also by Component
# We'll use facet_grid instead of facet_wrap, so that columns correspond to components and rows correspond to the different sagittal slices
(
    ggplot(data=df_template, mapping=aes(x="y", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(data=df_components_all, mapping=aes(fill="intensity"))
    + scale_fill_gradient(
        name="Component\nvalue",
        low="darkred",
        high="yellow",
        limits=(0.3, 0.5),
        na_value="transparent",
    )
    + scale_x_continuous(expand=(0, 0))
    + scale_y_continuous(expand=(0, 0))
    + facet_grid("slice_world ~ Component")
    + coord_equal(ratio=1)
    + theme_void()
    + theme(
        strip_text_y=element_blank(),
        panel_spacing=0,
    )
)
```

# Slice locator
```r
r

ggplot(data=(df_template_coronal_locator),
                  mapping=aes(x=x, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  theme_void() 
```
```python
python

(
    ggplot(data=df_template_coronal_locator, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + coord_equal(ratio=1)
    + theme_void()
)
```

```r
r

# Create a data frame called locator_bar_locs, which has a column called bar_locations
locator_bar_locs <- data.frame(bar_locations=slice_axis_coordinates)

# See what this looks like
locator_bar_locs
```
```python
python

# Create a data frame called locator_bar_locs, which has a column called bar_locations
locator_bar_locs = pandas.DataFrame({"bar_locations": slice_axis_coordinates})

# See what this looks like
locator_bar_locs
```

```r
r

ggplot(data=(df_template_coronal_locator),
                  mapping=aes(x=x, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  geom_vline(data=locator_bar_locs, mapping=aes(xintercept=bar_locations), color='red') +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  theme_void() 
```
```python
python

(
    ggplot(data=df_template_coronal_locator, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + geom_vline(
        data=locator_bar_locs,
        mapping=aes(xintercept="bar_locations"),
        color="red",
    )
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + coord_equal(ratio=1)
    + theme_void()
)
```

```r
r

ggplot(data=(df_template_coronal_locator),
                  mapping=aes(x=x, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  geom_vline(data=locator_bar_locs, mapping=aes(xintercept=bar_locations), color='red', lty=2) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  theme_void() 
```
```python
python

(
    ggplot(data=df_template_coronal_locator, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + geom_vline(
        data=locator_bar_locs,
        mapping=aes(xintercept="bar_locations"),
        color="red",
        linetype="dashed",
    )
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + coord_equal(ratio=1)
    + theme_void()
)
```


```r
r

ggplot(data=(df_template_coronal_locator %>% filter(mask_value > 0.5, intensity > 40)),
                  mapping=aes(x=x, y=z)) +
  geom_raster(mapping=aes(fill=intensity), interpolate = T) +
  geom_vline(data=locator_bar_locs, mapping=aes(xintercept=bar_locations), color='red', lty=1, linewidth=2) +
  scale_fill_gradient(low='black', high='white', limits=c(30, 90), oob=squish, guide='none') +
  coord_fixed(ratio=1) +
  theme_void() 
```
```python
python

(
    ggplot(
        data=df_template_coronal_locator[
            (df_template_coronal_locator["mask_value"] > 0.5)
            & (df_template_coronal_locator["intensity"] > 40)
        ],
        mapping=aes(x="x", y="z"),
    )
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + geom_vline(
        data=locator_bar_locs,
        mapping=aes(xintercept="bar_locations"),
        color="red",
        linetype="solid",  
        size=2,
    )
    + scale_fill_gradient(
        low="black", high="white", limits=(30, 90), oob=squish, guide=None
    )
    + coord_equal(ratio=1)
    + theme_void()
)
```

# Visualizing atlases and labels
# Overlay an atlas on a template
```r
r

df_template %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  coord_fixed(ratio=1) +
  theme_void()
```
```python
python

(
    ggplot(data=df_template, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(35, 80), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(
        data=df_atlas.assign(label_mod=lambda df: df["label"] % 8),
        mapping=aes(fill="label_mod"),
        alpha=0.5,
        interpolation="nearest",
    )
    + scale_fill_distiller(palette="Set3", guide=None)
    + coord_equal(ratio=1)
    + theme_void()
)
```

```r
r

# Mask out non-brain voxels
df_template_masked <- df_template %>%
  filter(mask_value > 0.5)

df_atlas_masked <- df_atlas %>% 
  filter(mask_value > 0.5)

# Use these to plot instead
df_template_masked %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  coord_fixed(ratio=1) +
  theme_void()
```

```python
python

# Mask out non-brain voxels
df_template_masked = df_template[df_template["mask_value"] > 0.5]
df_atlas_masked = df_atlas[df_atlas["mask_value"] > 0.5]

# Use these to plot instead
(
    ggplot(data=df_template_masked, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(35, 80), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(
        data=df_atlas_masked.assign(label_mod=lambda df: df["label"] % 8),
        mapping=aes(fill="label_mod"),
        alpha=0.5,
        interpolation="nearest",
    )
    + scale_fill_distiller(palette="Set3", guide=None)
    + coord_equal(ratio=1)
    + theme_void()
)
```

# Focus on a specific structure
```r
r

df_template_masked %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  scale_x_continuous(name="Left-Right", breaks=seq(from=-80, to=80, by=10)) +
  scale_y_continuous(name="Inferior-Superior", breaks=seq(from=-80, to=80, by=10)) +
  coord_fixed(ratio=1) +
  theme_bw()
```
```python
python

(
    ggplot(data=df_template_masked, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(35, 80), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(
        data=df_atlas_masked.assign(label_mod=lambda df: df["label"] % 8),
        mapping=aes(fill="label_mod"),
        alpha=0.5,
        interpolation="nearest",
    )
    + scale_fill_distiller(palette="Set3", guide=None)
    + scale_x_continuous(
        name="Left-Right",
        breaks=range(-80, 81, 10),
    )
    + scale_y_continuous(
        name="Inferior-Superior",
        breaks=range(-80, 81, 10),
    )
    + coord_equal(ratio=1)
    + theme_bw()
)
```

```r
r

df_template_masked %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  scale_x_continuous(name="Left-Right", breaks=seq(from=-80, to=80, by=10)) +
  scale_y_continuous(name="Inferior-Superior", breaks=seq(from=-80, to=80, by=10)) +
  geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill='transparent', color='red') +
  coord_fixed(ratio=1) +
  theme_bw()
```
```python
python

(
    ggplot(data=df_template_masked, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(35, 80), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(
        data=df_atlas_masked.assign(label_mod=lambda df: df["label"] % 8),
        mapping=aes(fill="label_mod"),
        alpha=0.5,
        interpolation="nearest",
    )
    + scale_fill_distiller(palette="Set3", guide=None)
    + scale_x_continuous(
        name="Left-Right",
        breaks=range(-80, 81, 10),
    )
    + scale_y_continuous(
        name="Inferior-Superior",
        breaks=range(-80, 81, 10),
    )
    + geom_rect(
        xmin=-10,
        xmax=30,
        ymin=-10,
        ymax=30,
        fill="none",
        color="red",
    )
    + coord_equal(ratio=1)
    + theme_bw()
)
```

```r
r

# Do the filtering
df_template_masked_filtered <- df_template %>%
  filter(mask_value > 0.5, x >= -10, x <= 30, z >= -10, z <= 30)

df_atlas_masked_filtered <- df_atlas %>% 
  filter(mask_value > 0.5, x >= -10, x <= 30, z >= -10, z <= 30)

# Used filtered data for the plot
df_template_masked_filtered %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked_filtered, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill='transparent', color='red') +
  coord_fixed(ratio=1) +
  theme_void()
```
```python
python

# Do the filtering
df_template_masked_filtered = df_template[
    (df_template["mask_value"] > 0.5)
    & (df_template["x"] >= -10)
    & (df_template["x"] <= 30)
    & (df_template["z"] >= -10)
    & (df_template["z"] <= 30)
]

df_atlas_masked_filtered = df_atlas[
    (df_atlas["mask_value"] > 0.5)
    & (df_atlas["x"] >= -10)
    & (df_atlas["x"] <= 30)
    & (df_atlas["z"] >= -10)
    & (df_atlas["z"] <= 30)
]

# Used filtered data for the plot
(
    ggplot(data=df_template_masked_filtered, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(35, 80), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(
        data=df_atlas_masked_filtered.assign(
            label_mod=lambda df: df["label"] % 8
        ),
        mapping=aes(fill="label_mod"),
        alpha=0.5,
        interpolation="nearest",
    )
    + scale_fill_distiller(palette="Set3", guide=None)
    + geom_rect(
        xmin=-10,
        xmax=30,
        ymin=-10,
        ymax=30,
        fill="none",
        color="red",
    )
    + coord_equal(ratio=1)
    + theme_void()
)
```

# Annotate labels
```r
r

# Left join the above
df_atlas_masked_filtered_with_defs <- df_atlas_masked_filtered %>%
  left_join(atlas_defs, by="label")

# See what the joined data looks like
# Note the additional columns that now exist in the data frame
df_atlas_masked_filtered_with_defs
```
```python
python

# Left join the above
df_atlas_masked_filtered_with_defs = df_atlas_masked_filtered.merge(
    atlas_defs, on="label", how="left"
)

# See what the joined data looks like
# Note the additional columns that now exist in the data frame
df_atlas_masked_filtered_with_defs
```

```r
r

# Save as new data frame: df_labels
df_labels <- df_atlas_masked_filtered_with_defs %>%
  filter(x > 0) %>%
  group_by(structure_acronym) %>%
  summarize(label_pos_x=median(x), label_pos_z=median(z))
```
```python
python

# Save as new data frame: df_labels
df_labels = (
    df_atlas_masked_filtered_with_defs[df_atlas_masked_filtered_with_defs["x"] > 0]
    .groupby("structure_acronym")
    .agg(label_pos_x=("x", "median"), label_pos_z=("z", "median"))
    .reset_index()
)
```

```r
r

df_template_masked_filtered %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked_filtered, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  geom_text(aes(x=label_pos_x, y=label_pos_z, label=structure_acronym), data=df_labels) +
  geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill='transparent', color='red') +
  coord_fixed(ratio=1) +
  theme_void()
```
```python
python

(
    ggplot(data=df_template_masked_filtered, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(35, 80), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(
        data=df_atlas_masked_filtered.assign(
            label_mod=lambda df: df["label"] % 8
        ),
        mapping=aes(fill="label_mod"),
        alpha=0.5,
        interpolation="nearest",
    )
    + scale_fill_distiller(palette="Set3", guide=None)
    + geom_text(
        data=df_labels,
        mapping=aes(x="label_pos_x", y="label_pos_z", label="structure_acronym"),
    )
    + geom_rect(
        xmin=-10,
        xmax=30,
        ymin=-10,
        ymax=30,
        fill="none",
        color="red",
    )
    + coord_equal(ratio=1)
    + theme_void()
)
```

```r
r

# Filter away labels near the edge
df_labels_filtered <- df_labels %>%
  filter(label_pos_x < 27, label_pos_z > -7, label_pos_z < 27)

# Replot
df_template_masked_filtered %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked_filtered, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  geom_text(aes(x=label_pos_x, y=label_pos_z, label=structure_acronym), data=df_labels_filtered) +
  geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill='transparent', color='red') +
  coord_fixed(ratio=1) +
  theme_void()
```
```python
python

# Filter away labels near the edge
df_labels_filtered = df_labels[
    (df_labels["label_pos_x"] < 27)
    & (df_labels["label_pos_z"] > -7)
    & (df_labels["label_pos_z"] < 27)
]

# Replot
(
    ggplot(data=df_template_masked_filtered, mapping=aes(x="x", y="z"))
    + geom_raster(mapping=aes(fill="intensity"), interpolation="bilinear")
    + scale_fill_gradient(
        low="black", high="white", limits=(35, 80), oob=squish, guide=None
    )
    + new_scale_fill()
    + geom_raster(
        data=df_atlas_masked_filtered.assign(
            label_mod=lambda df: df["label"] % 8
        ),
        mapping=aes(fill="label_mod"),
        alpha=0.5,
        interpolation="nearest",
    )
    + scale_fill_distiller(palette="Set3", guide=None)
    + geom_text(
        data=df_labels_filtered,
        mapping=aes(x="label_pos_x", y="label_pos_z", label="structure_acronym"),
    )
    + geom_rect(
        xmin=-10,
        xmax=30,
        ymin=-10,
        ymax=30,
        fill="none",
        color="red",
    )
    + coord_equal(ratio=1)
    + theme_void()
)
```

# Combine plots with patchwork
```r
r

# Full brain plot
plt_full_brain <- df_template_masked %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  scale_x_continuous(name="Left-Right", breaks=seq(from=-80, to=80, by=10)) +
  scale_y_continuous(name="Inferior-Superior", breaks=seq(from=-80, to=80, by=10)) +
  geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill='transparent', color='red') +
  coord_fixed(ratio=1) +
  theme_void()

plt_zoomed_in <- df_template_masked_filtered %>%
  ggplot(aes(x=x, y=z)) +
  geom_raster(aes(fill=intensity), interpolate = T) +
  scale_fill_gradient(low='black', high='white', 
                      limits=c(35, 80), oob=squish,
                      guide="none") +
  new_scale_fill() +
  geom_raster(aes(fill=(label %% 8)), data=df_atlas_masked_filtered, alpha=0.5, interpolate=F) +
  scale_fill_distiller(palette = "Set3", guide="none") +
  geom_text(aes(x=label_pos_x, y=label_pos_z, label=structure_acronym), data=df_labels_filtered) +
  geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill='transparent', color='red') +
  coord_fixed(ratio=1) +
  theme_void()

# Patchwork provides / as a shorthand for placing plots vertically
plt_full_brain / plt_zoomed_in
```
```python
python

# Full Brain Plot
plt_full_brain = (
    ggplot(df_template_masked, aes(x="x", y="z"))
    # Base template mapped to alpha (over black background) to mimic gray gradient
    + geom_raster(aes(alpha="intensity"), fill="white", interpolate=True)
    + scale_alpha_continuous(range=(0, 1), limits=(35, 80), oob=squish, guide=None)
    # Map the Atlas fill. Modulo in Python uses '%' and discrete fills need 'factor()'
    + geom_raster(
        aes(fill="factor(label % 8)"), 
        data=df_atlas_masked, 
        alpha=0.5, 
        interpolate=False
    )
    + scale_fill_brewer(type="qual", palette="Set3", guide=None)
    # Continuous Scales
    + scale_x_continuous(name="Left-Right", breaks=np.arange(-80, 81, 10))
    + scale_y_continuous(name="Inferior-Superior", breaks=np.arange(-80, 81, 10))
    # Red Region of Interest Box
    + geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill="none", color="red")
    + coord_fixed(ratio=1)
    + theme_void()
    # Dark panel background is necessary for the white-on-black alpha gradient
    + theme(panel_background=element_rect(fill="black"))
)

# Zoomed-In Plot
plt_zoomed_in = (
    ggplot(df_template_masked_filtered, aes(x="x", y="z"))
    + geom_raster(aes(alpha="intensity"), fill="white", interpolate=True)
    + scale_alpha_continuous(range=(0, 1), limits=(35, 80), oob=squish, guide=None)
    + geom_raster(
        aes(fill="factor(label % 8)"), 
        data=df_atlas_masked_filtered, 
        alpha=0.5, 
        interpolate=False
    )
    + scale_fill_brewer(type="qual", palette="Set3", guide=None)
    # Labeled structures
    + geom_text(
        aes(x="label_pos_x", y="label_pos_z", label="structure_acronym"), 
        data=df_labels_filtered
    )
    + geom_rect(xmin=-10, xmax=30, ymin=-10, ymax=30, fill="none", color="red")
    + coord_fixed(ratio=1)
    + theme_void()
    + theme(panel_background=element_rect(fill="black"))
)

# Convert plotnine objects into patchworklib Bricks
plt_full = pw.load_ggplot(plt_full_brain, figsize=(6, 5))
plt_zoom = pw.load_ggplot(plt_zoomed_in, figsize=(6, 5))

# Use / to place plots vertically 
combined_plot = plt_full / plt_zoom
combined_plot.savefig()  
```

```r
r

# Plots can also be stacked horizontally using +
plt_full_brain + plt_zoomed_in
```
```python
python

# Plots can also be stacked horizontally using | (or +)
combined_plot = plt_full | plt_zoom
combined_plot.savefig()
```