# Resolve the shared geometry/axis/coordinate arguments for slice_grid(),
# which (unlike slice_image()/slice_contours()) needs no image sampling at
# all -- `image` exists only to feed build_slice_geometry() when `geometry`
# isn't supplied directly.
.resolve_geometry_only <- function(image, axis, coordinate, geometry) {
  has_geometry <- !is.null(geometry)
  if (has_geometry && (!is.null(axis) || !is.null(coordinate))) {
    stop("`axis`/`coordinate` must not be supplied together with `geometry`.", call. = FALSE)
  }
  if (!has_geometry && (is.null(axis) || is.null(coordinate))) {
    stop("Provide either `geometry`, or both `axis` and `coordinate`.", call. = FALSE)
  }
  if (has_geometry) {
    return(.as_slice_package_set(geometry))
  }
  if (is.null(image)) {
    stop("`image` is required when `geometry` is not supplied.", call. = FALSE)
  }
  if (is.character(image)) image <- ReadImage_fix(image)
  check_sitk_image(image)
  build_slice_geometry(image, axis, coordinate)
}

# Build every box/grid line for a single SliceGeometry, in local in-plane
# coordinates mapped to world space via that slice's own origin/direction_i/
# direction_j. Both box and grid lines are generated by the same code: the
# box is just 2 lines per axis, at the (padded) extremes.
.slice_grid_lines <- function(slice_geom, spacing, point_spacing, padding) {
  extent <- slice_geom$get_extent()
  if (any(extent + 2 * padding <= 0)) {
    stop("`padding` is too large (negative) relative to the slice's extent.", call. = FALSE)
  }
  if (is.null(spacing)) spacing <- min(extent) / 10
  if (is.null(point_spacing)) point_spacing <- spacing / 20

  origin <- slice_geom$get_origin()
  di <- slice_geom$get_direction_i()
  dj <- slice_geom$get_direction_j()

  build_lines_for_axis <- function(grid_axis, grid_coords, part) {
    line_extent_len <- if (grid_axis == "i") extent[2] else extent[1]
    line_start <- 0 - padding
    line_end <- line_extent_len + padding
    n_line_pts <- max(2, round((line_end - line_start) / point_spacing) + 1)
    line_coords <- seq(line_start, line_end, length.out = n_line_pts)

    dplyr::bind_rows(lapply(seq_along(grid_coords), function(line_id) {
      gc <- grid_coords[line_id]
      if (grid_axis == "i") {
        local_i <- rep(gc, n_line_pts)
        local_j <- line_coords
      } else {
        local_i <- line_coords
        local_j <- rep(gc, n_line_pts)
      }
      world <- matrix(origin, nrow = n_line_pts, ncol = 3, byrow = TRUE) +
        outer(local_i, di) + outer(local_j, dj)
      tibble::tibble(
        part = part, grid_axis = grid_axis, line_id = line_id,
        vertex = seq_len(n_line_pts),
        x = world[, 1], y = world[, 2], z = world[, 3]
      )
    }))
  }

  box_i_coords <- c(0 - padding, extent[1] + padding)
  box_j_coords <- c(0 - padding, extent[2] + padding)
  box <- dplyr::bind_rows(
    build_lines_for_axis("i", box_i_coords, "box"),
    build_lines_for_axis("j", box_j_coords, "box")
  )

  grid_i_coords <- seq(0 - padding, extent[1] + padding, by = spacing)
  grid_j_coords <- seq(0 - padding, extent[2] + padding, by = spacing)
  grid <- dplyr::bind_rows(
    build_lines_for_axis("i", grid_i_coords, "grid"),
    build_lines_for_axis("j", grid_j_coords, "grid")
  )

  dplyr::bind_rows(box, grid)
}

#' Build a box + gridline overlay for a slice (or slices)
#'
#' @description
#' Computes an overlay grid for each slice in the requested geometry: an
#' outer bounding box plus evenly-spaced horizontal and vertical lines
#' (same spacing in both directions), each line a densely-sampled ordered
#' set of points suitable for `ggplot2::geom_path()`. Typical uses: a visual
#' reference grid over an anatomical slice, or (combined with
#' [transform_points()]) a grid warped through a registration transform, to
#' visualize what that transform does to the image.
#'
#' Unlike [slice_image()]/[slice_contours()], no image is sampled here — the
#' grid is pure geometry, computed entirely from the resolved
#' [SliceGeometry]/[SlicePackage]/[SlicePackageSet]. `image` (with
#' `axis`/`coordinate`) exists only for interface consistency with those
#' functions, feeding [build_slice_geometry()] when `geometry` isn't
#' supplied directly.
#'
#' @param image A `SimpleITK` image, or a file path (read internally via
#'   [ReadImage_fix()]). Required unless `geometry` is supplied.
#' @param axis Which image axis is out-of-plane (see [build_slice_geometry()]).
#'   Required unless `geometry` is supplied; must not be supplied together
#'   with `geometry`.
#' @param coordinate One or more world coordinates along `axis` (see
#'   [build_slice_geometry()]). Required unless `geometry` is supplied; must
#'   not be supplied together with `geometry`.
#' @param spacing Distance between adjacent gridlines, the same for both
#'   horizontal and vertical. Defaults (if `NULL`) to `min(extent) / 10`,
#'   scale-adaptive so it's reasonable whether the slice is measured in mm
#'   or µm.
#' @param point_spacing Distance between points along a single line,
#'   controlling how smooth/coarse it looks when plotted. Defaults (if
#'   `NULL`) to `spacing / 20`.
#' @param padding Extend (positive) or inset (negative) the box beyond the
#'   slice's true extent. Default `0` (exact bounds).
#' @param geometry A pre-built [SliceGeometry]/[SlicePackage]/[SlicePackageSet],
#'   used instead of `axis`/`coordinate`. Must not be supplied together with
#'   `axis`/`coordinate`.
#' @return A tibble with columns `package`, `k`, `part` (`"box"` or
#'   `"grid"`), `grid_axis` (`"i"` or `"j"`: which in-plane axis is held
#'   fixed along this line), `line_id` (distinguishes different lines
#'   sharing the same `part`/`grid_axis`), `vertex` (1-based order within
#'   the line), `x`, `y`, `z` (world coordinates).
#' @examples
#' \dontrun{
#' image <- ReadImage_fix("brain_image.nii")
#' grid_df <- slice_grid(image, axis = "axial", coordinate = 0, spacing = 5)
#' }
#' @export
slice_grid <- function(image = NULL, axis = NULL, coordinate = NULL,
                        spacing = NULL, point_spacing = NULL, padding = 0,
                        geometry = NULL) {
  if (!is.null(spacing) && (!is.numeric(spacing) || length(spacing) != 1 || spacing <= 0)) {
    stop("`spacing` must be a single positive number (or NULL for the default).", call. = FALSE)
  }
  if (!is.null(point_spacing) && (!is.numeric(point_spacing) || length(point_spacing) != 1 || point_spacing <= 0)) {
    stop("`point_spacing` must be a single positive number (or NULL for the default).", call. = FALSE)
  }
  if (!is.numeric(padding) || length(padding) != 1) {
    stop("`padding` must be a single number.", call. = FALSE)
  }

  package_set <- .resolve_geometry_only(image, axis, coordinate, geometry)

  results <- list()
  for (pkg_name in package_set$get_package_names()) {
    pkg <- package_set$get_packages()[[pkg_name]]
    n_k <- pkg$get_size_k()
    for (k in 0:(n_k - 1)) {
      slice_geom <- pkg$get_slice(k)
      lines <- .slice_grid_lines(slice_geom, spacing, point_spacing, padding)
      lines$package <- pkg_name
      lines$k <- k
      results[[length(results) + 1]] <- lines
    }
  }

  out <- dplyr::bind_rows(results)
  dplyr::select(out, "package", "k", "part", "grid_axis", "line_id", "vertex", "x", "y", "z")
}

#' Ready-made ggplot2 layers for a grid produced by slice_grid()
#'
#' @description
#' `slice_grid()`'s box and grid lines are two visually-distinct components
#' that normally need two separate `geom_path()` calls with different
#' styling. This returns both as ready-made, composable layers to `+` onto
#' a plot, rather than requiring the user to filter `part` and write the
#' grouping expression themselves.
#'
#' @param grid_df A data frame as returned by [slice_grid()].
#' @param box_color,box_linewidth,box_alpha Style for the box layer.
#' @param grid_color,grid_linewidth,grid_alpha Style for the grid layer.
#' @return A named list with elements `box` and `grid`, each a
#'   `ggplot2::geom_path()` layer. Add both (e.g. `plt + layers$box + layers$grid`)
#'   to a plot that already maps `x`/`y` via its own `aes()`.
#' @examples
#' \dontrun{
#' image <- ReadImage_fix("brain_image.nii")
#' grid_df <- slice_grid(image, axis = "axial", coordinate = 0, spacing = 5)
#' layers <- slice_grid_layers(grid_df)
#'
#' library(ggplot2)
#' ggplot(grid_df, aes(x = x, y = y)) + layers$box + layers$grid
#' }
#' @importFrom rlang .data
#' @export
slice_grid_layers <- function(grid_df,
                               box_color = "orange", box_linewidth = 1, box_alpha = 1,
                               grid_color = "#FF6666", grid_linewidth = 0.25, grid_alpha = 0.8) {
  # Use the unqualified `.data` pronoun here, not `rlang::.data` -- confirmed
  # directly (see CLAUDE.md) that ggplot2's tidy-eval data mask only
  # special-cases the bare `.data` symbol; `rlang::.data$x` parses to a `::`
  # call that isn't recognized the same way and throws "Can't subset `.data`
  # outside of a data mask context" the moment the plot is actually built
  # (not merely constructed) -- a real, previously-undetected bug this
  # project's own tests never caught because they never called
  # ggplot2::ggplot_build() on the result.
  group_mapping <- ggplot2::aes(group = interaction(
    .data$package, .data$k, .data$grid_axis, .data$line_id
  ))

  box_layer <- ggplot2::geom_path(
    data = grid_df[grid_df$part == "box", ],
    mapping = group_mapping,
    color = box_color, linewidth = box_linewidth, alpha = box_alpha
  )
  grid_layer <- ggplot2::geom_path(
    data = grid_df[grid_df$part == "grid", ],
    mapping = group_mapping,
    color = grid_color, linewidth = grid_linewidth, alpha = grid_alpha
  )

  list(box = box_layer, grid = grid_layer)
}
